baseURL = 'https://tamada.github.io/welfare-time/'
locale = 'ja'
title = 'Welfare-Time'

[params]
  brand_icon = "assets/icon.svg"
  googleAnalytics4 = "G-16KW5F4YZC"

[markup.goldmark.renderer]
unsafe = true

[[menus.main]]
  name = "カード"
  url = "/"
  params = { icon = "bi-grid-fill" }
  weight = 10
[[menus.main]]
  name = "マップ"
  url = "/map/"
  params = { icon = "bi-map" }
  weight = 30
[[menus.main]]
  name = "GitHub"
  url = "https://github.com/tamada/welfare-time"
  params = { icon = "bi-github" }
  weight = 40
[[menus.main]]
  name = "ヘルプ"
  url = "/help/"
  params = { icon = "bi-question-circle" }
  weight = 50
